export default {
  LOAD_REVIEW_START: 'LOAD_REVIEW_START',
  LOAD_REVIEW_SUCCESS: 'LOAD_REVIEW_SUCCESS',
  LOAD_REVIEW_ERROR: 'LOAD_REVIEW_ERROR',
  LOAD_REVIEW_FINISH: 'LOAD_REVIEW_FINISH',

  CREATE_REVIEW_START: 'SEND_NEW_REVIEW_START',
  CREATE_REVIEW_SUCCESS: 'SEND_NEW_REVIEW_SUCCESS',
  CREATE_REVIEW_ERROR: 'SEND_NEW_REVIEW_ERROR',
  CREATE_REVIEW_FINISH: 'SEND_NEW_REVIEW_FINISH',

};
