export default {
  LOAD_DATA_START: 'LOAD_DATA_START',
  LOAD_COUNTRIES_INDEXES_SUCCESS: 'LOAD_COUNTRIES_INDEXES_SUCCESS',
  LOAD_DATA_SUCCESS: 'LOAD_DATA_SUCCESS',
  LOAD_DATA_ERROR: 'LOAD_DATA_ERROR',
  LOAD_DATA_FINISH: 'LOAD_DATA_FINISH',

  UPDATE_COUNTRY_INDEXES: 'UPDATE_COUNTRY_INDEXES',
  UPDATE_COUNTRIES_INDEXES: 'UPDATE_COUNTRIES_INDEXES',

  CHANGE_COUNTRY_PERCENT: 'CHANGE_COUNTRY_PERCENT',
  CHANGE_DIRECTION: 'CHANGE_DIRECTION',
  CHOSE_GIVE_OPTION: 'CHOSE_GIVE_OPTION',
  CHOSE_GET_OPTION: 'CHOSE_GET_OPTION',
  CHANGE_GIVE_AMOUNT: 'CHANGE_GIVE_AMOUNT',
  CHANGE_GET_AMOUNT: 'CHANGE_GET_AMOUNT',
  CHOOSE_VARIANT_OPTION: 'CHOOSE_VARIANT_OPTION',

  CHANGE_CARD_VALUE: 'CHANGE_CARD_VALUE',
  CHANGE_WALLET_VALUE: 'CHANGE_WALLET_VALUE',
  CHANGE_ACCOUNT_VALUE: 'CHANGE_ACCOUNT_VALUE',
  CHANGE_DELIVER_COUNTY_OPTION: 'CHANGE_DELIVER_COUNTY_OPTION',
  CHANGE_DELIVER_CITY_OPTION: 'CHANGE_DELIVER_CITY_OPTION',
  CHANGE_DELIVER_VALUE: 'CHANGE_DELIVER_VALUE',
  CHANGE_PRIVACY_VALUE: 'CHANGE_PRIVACY_VALUE',
  CHANGE_REMEMBER_VALUE: 'CHANGE_REMEMBER_VALUE',

  CHANGE_TRANSACTION_STATUS: 'CHANGE_TRANSACTION_STATUS',

  NEXT_STEP: 'NEXT_STEP',
  PREVIOUS_STEP: 'PREVIOUS_STEP',

  FINISH_STEP: 'FINISH_STEP',
  RESET_EXCHANGE: 'RESET_EXCHANGE',
};
