export default {
  LOAD_DATA: 'LOAD_DATA',
  CHANGE_COUNTRY_PERCENT: 'CHANGE_COUNTRY_PERCENT',
  CHANGE_DIRECTION: 'CHANGE_DIRECTION',
  CHOSE_GIVE_OPTION: 'CHOSE_GIVE_OPTION',
  CHOSE_GET_OPTION: 'CHOSE_GET_OPTION',
  CHANGE_GIVE_AMOUNT: 'CHANGE_GIVE_AMOUNT',
  CHANGE_GET_AMOUNT: 'CHANGE_GET_AMOUNT',
  CHOOSE_VARIANT_OPTION: 'CHOOSE_VARIANT_OPTION',

  CHANGE_CARD_VALUE: 'CHANGE_CARD_VALUE',
  CHANGE_WALLET_VALUE: 'CHANGE_WALLET_VALUE',
  CHANGE_ACCOUNT_VALUE: 'CHANGE_ACCOUNT_VALUE',
  CHANGE_DELIVER_COUNTY_OPTION: 'CHANGE_DELIVER_COUNTY_OPTION',
  CHANGE_DELIVER_CITY_OPTION: 'CHANGE_DELIVER_CITY_OPTION',
  CHANGE_DELIVER_VALUE: 'CHANGE_DELIVER_VALUE',
  CHANGE_PRIVACY_VALUE: 'CHANGE_PRIVACY_VALUE',
  CHANGE_REMEMBER_VALUE: 'CHANGE_REMEMBER_VALUE',

  NEXT_STEP: 'NEXT_STEP',
  PREVIOUS_STEP: 'PREVIOUS_STEP',
};
