export default {
  LOAD_DATA: 'LOAD_DATA',
  CHANGE_COUNTRY_PERCENT: 'CHANGE_COUNTRY_PERCENT',
  CHANGE_DIRECTION: 'CHANGE_DIRECTION',
  CHOSE_GIVE_OPTION: 'CHOSE_GIVE_OPTION',
  CHOSE_GET_OPTION: 'CHOSE_GET_OPTION',
  CHANGE_GIVE_AMOUNT: 'CHANGE_GIVE_AMOUNT',
  CHANGE_GIVE_AMOUNT_ERROR: 'CHANGE_GIVE_AMOUNT_ERROR',
  CHANGE_GET_AMOUNT: 'CHANGE_GET_AMOUNT',
  CHANGE_GET_AMOUNT_ERROR: 'CHANGE_GET_AMOUNT_ERROR',
  CHOOSE_VARIANT_OPTION: 'CHOOSE_VARIANT_OPTION',
  NEXT_STEP: 'NEXT_STEP',
};
