export default {
  LOAD_FAQ_START: 'LOAD_FAQ_START',
  LOAD_FAQ_SUCCESS: 'LOAD_FAQ_SUCCESS',
  LOAD_FAQ_ERROR: 'LOAD_FAQ_ERROR',
  LOAD_FAQ_FINISH: 'LOAD_FAQ_FINISH',

  SEARCH_BY_TEXT: 'SEARCH_BY_TEXT',
  CHANGE_CHOSEN_TAGS: 'CHANGE_CHOSEN_TAGS',
}
