export default {
  // app
  APP_START: 'APP_START',
  APP_SUCCESS: 'APP_SUCCESS',
  APP_ERROR: 'APP_ERROR',
  APP_FINISH: 'APP_FINISH',

  // socket
  SOCKET_CONNECTING_START: 'SOCKET_CONNECTING_START',
  SOCKET_CONNECTING_SUCCESS: 'SOCKET_CONNECTING_SUCCESS',
  SOCKET_CONNECTING_ERROR: 'SOCKET_CONNECTING_ERROR',

  CHANGE_WINDOW_SIZE: 'CHANGE_WINDOW_SIZE',
  TOGGLE_PRIVACY_MODAL: 'TOGGLE_PRIVACY_MODAL',

  TOGGLE_MODAL: 'TOGGLE_MODAL',

  // map
  LOAD_PIN_START: 'LOAD_PIN_START',
  LOAD_PIN_SUCCESS: 'LOAD_PIN_SUCCESS',
  LOAD_PIN_ERROR: 'LOAD_PIN_ERROR',
  LOAD_PIN_FINISH: 'LOAD_PIN_FINISH',

  // banner
  LOAD_BANNER_START: 'LOAD_BANNER_START',
  LOAD_BANNER_SUCCESS: 'LOAD_BANNER_SUCCESS',
  LOAD_BANNER_ERROR: 'LOAD_BANNER_ERROR',
  LOAD_BANNER_FINISH: 'LOAD_BANNER_FINISH',

  // chart
  TOGGLE_TIME_PERIOD: 'TOGGLE_TIME_PERIOD',
  CHANGE_CHART: 'CHANGE_CHART',
  LOAD_CHART_DATA_START: 'LOAD_CHART_DATA_START',
  LOAD_CHART_DATA_SUCCESS: 'LOAD_CHART_DATA_SUCCESS',
  LOAD_CHART_DATASET_UPDATE: 'LOAD_CHART_DATASET_UPDATE',
  LOAD_CHART_DATASET_UPDATED: 'LOAD_CHART_DATASET_UPDATED',
  LOAD_CHART_DATA_ERROR: 'LOAD_CHART_DATA_ERROR',
  LOAD_CHART_DATA_FINISH: 'LOAD_CHART_DATA_FINISH',
};
