export default {
  CHANGE_WINDOW_SIZE: 'CHANGE_WINDOW_SIZE',
  TOGGLE_PRIVACY_MODAL: 'TOGGLE_PRIVACY_MODAL',

  TOGGLE_MODAL: 'TOGGLE_MODAL',

  LOAD_PIN_START: 'LOAD_PIN_START',
  LOAD_PIN_SUCCESS: 'LOAD_PIN_SUCCESS',
  LOAD_PIN_ERROR: 'LOAD_PIN_ERROR',
  LOAD_PIN_FINISH: 'LOAD_PIN_FINISH',
};
